name: Vancouver

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * 0'

jobs:
  python:
    name: Send Victoria Civil Data to Email
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.6' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    # You can test your matrix by printing the current Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Test Cases
      run: |
        python main.py --input_job "Civil Engineer" --input_city Victoria --input_state BC
      env:
        MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
        MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
