name: Pull Data and build

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '.github/workflows/*.yml'

jobs:
  python:
    name: Pull Data from Indeed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.6' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Test Cases
      run: |
        coverage run -m pytest tests/*.py
        coverage report
        coverage html
        coverage xml
        coverage json
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./coverage.xml #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
        yml: ./codecov.yml #optional
        fail_ci_if_error: true #optional (default = false)
    - name: Uploading tex document
      uses: actions/upload-artifact@v1
      with:
        name: indeed
        path: sample.tex

  build_latex:
    name: Build Tex File
    needs: python
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: indeed
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: indeed/sample.tex
      - name: Checking directory files
        run: |
          ls
      - name: Uploading pdf document
        uses: actions/upload-artifact@v2
        with:
          name: tex
          path: sample.pdf
