name: Setup python 3.6

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.6' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Test Cases
      run: |
        coverage run -m pytest test/*.py
        coverage report
        coverage html
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./coverage.xml #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
        yml: ./codecov.yml #optional
        fail_ci_if_error: true #optional (default = false)
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./coverage.xml #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
        yml: ./codecov.yml #optional
        fail_ci_if_error: true #optional (default = false)
    