name: Scheduled Build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'


jobs:
  python:
    name: Pull Data from Indeed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.6' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    # You can test your matrix by printing the current Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Test Cases
      run: |
        python main.py $email_from $email_password $email_to
      env:
        email_from: ${{ secrets.INDEED_EMAIL }}
        email_password: ${{ secrets.INDEED_PASSWORD }}
        email_to: ${{ secrets.TEST_EMAIL }}